project:
  type: book
  output-dir: docs

book:
  title: "TROLL V4 Evaluation"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_data.qmd
      chapters: 
        - 11_inventories.qmd
        - 12_species.qmd
        - 13_soil.qmd
        - 14_climate.qmd
        - 15_fluxes.qmd
    - part: 20_experiment.qmd
      chapters: 
        - 21_methods.qmd
        - 22_tools.qmd
    - part: 30_calibration.qmd
      chapters: 
        - 31_str3.qmd
        - 32_str4.qmd
        - 33_phenology.qmd
    - part: 40_evaluation.qmd
      chapters: 
        - 41_variation.qmd
        - 42_forest.qmd
        - 43_fluxes.qmd
        - 44_dynamics.qmd
  appendices:
    - 97_key_figure.qmd
    - 98_companion_figures.qmd
    - 99_references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1
    number-sections: false

editor: visual
