---
title: "TROLL V4 Evaluation"
author: Sylvain Schmitt -
date: today
date-format: medium
format: gfm
---

The aim of these analyses is to evaluate the TROLL version 4 simulations of daily fluxes and the final structure and composition of the forest in relation to field observations and remote sensing at two Amazonian sites. All steps (including data, methods, uses of singularity and snakemake) and results are described in the following document: <https://sylvainschmitt.github.io/troll_eval/> .

## Poeple

-   Sylvain Schmitt (sylvain.schmitt\@cirad.fr)

-   Fabian J. Fischer (f.fischer\@bristol.ac.uk)

-   James Ball (jgcb3\@cam.ac.uk)

-   Nicolas Barbier (nicolas.barbier\@ird.fr)

-   Marion Boisseaux (marionboisseaux\@gmail.com)

-   Damien Bonal (damien.bonal\@inrae.fr)

-   Benoit Burban (benoit.burban\@inrae.fr)

-   Xiuzhi Chen (henxzh73\@mail.sysu.edu.cn)

    Géraldine Derroire (geraldine.derroire\@cirad.fr)

-   Jeremy Lichstein (jlichstein\@ufl.edu)

-   Daniela Nemetschek (Daniela.Krebber\@ecofog.gf)

-   Natalia Restrepo-Coupe (nataliacoupe\@gmail.com)

-   Scott Saleska (saleska\@arizona.edu)

-   Giacomo Selan (giacomo.sellan\@cirad.fr)

-   Philippe Verley (philippe.verley\@ird.fr)

-   Gregoire Vincent (gregoire.vincent\@ird.fr)

-   Camille Ziegler (camille.ziegler9\@gmail.com)

-   Jérôme Chave (jerome.chave\@univ-tlse3.fr)

-   Isabelle Maréchaux (isabelle.marechaux\@inrae.fr)
