output: "calibration phenology"

# data
sites: "Paracou"
day_start: 7
day_end: 19

# calib structure
# paste0("[", paste(seq(1.8, 2.2, 0.01), collapse = ", "), "]")
cra: [1.85]
crberr: [-0.4641]
m: [0.045]

# selected structure
cra_f: 1.85
crb_f: 0.4445
crberr_f: -0.4641
m_f: 0.045

# calib pheno
a0: [0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5]
b0: [0.05, 0.01, 0.015, 0.02, 0.04, 0.06, 0.08, 0.10]
delta: [0.1, 0.2, 0.3, 0.4, 0.5]

# selected pheno
a0_f: 0.2
b0_f: 0.015
delta_f: 0.2

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 10

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: false
test_years: 0.1
