output: "evaluation"

# data
sites: "Tapajos"
day_start: 6
day_end: 18

# calib structure
# paste0("[", paste(seq(1.8, 2.2, 0.01), collapse = ", "), "]")
cra: [2.50]
crberr: [-0.25]
m: [0.045]

# selected structure
cra_f: 2.50
crb_f: 0.8150
crberr_f: -0.25
m_f: 0.045

# calib pheno
a0: [0.2]
b0: [0.015]
delta: [0.3]

# selected pheno
a0_f: 0.2
b0_f: 0.015
delta_f: 0.3

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 10

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: false
test_years: 0.1
