output: "evaluation"

# data
sites: "Paracou"
day_start: 7
day_end: 19

# calib structure
cra: 1.80
crberr: -0.25
m: 0.035

# selected structure
cra_f: 1.80
crb_f: 0.3860
crberr_f: -0.25
m_f: 0.035

# calib pheno
a0: [0.2]
b0: [0.015]
delta: [0.1]

# selected pheno
a0_f: 0.2
b0_f: 0.015
delta_f: 0.1

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 10

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: false
test_years: 0.1
