# data
sites: ["Paracou", "Tapajos"]
a0: [0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5]
b0: [0.05, 0.01, 0.015, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.14, 0.16, 0.18, 0.20]
delta: [0.1, 0.2, 0.3, 0.4, 0.5]

# sim pars
spinup: 600
verbose: yes
seed: 42 # for the random selection of years

# final pars
a0_f: 0.2
b0_f: 0.015
delta_f: 0.2
rep: 10

# singularity
# troll: "https://github.com/sylvainschmitt/singularity-troll/releases/download/0.0.3/sylvainschmitt-singularity-troll.latest.sif"
troll: "singularity/troll.sif"

# tests
test: false
test_years: 0.1
