output: "evaluation"

# data
sites: "Tapajos"
day_start: 6
day_end: 18

# calib structure
cra: 2.45
crberr: -0.25
m: 0.040

# selected structure
cra_f: 2.45
crb_f: 0.7565
crberr_f: -0.25
m_f: 0.040

# calib pheno
a0: [0.2]
b0: [0.015]
delta: [0.3]

# selected pheno
a0_f: 0.2
b0_f: 0.015
delta_f: 0.3

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 10

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: false
test_years: 0.1
