output: "calibration structure 4"

# data
sites: "Tapajos"
day_start: 6
day_end: 18

# calib structure
# paste0("[", paste(seq(1.8, 2.2, 0.01), collapse = ", "), "]")
cra: [2.3, 2.35, 2.4, 2.45, 2.5, 2.55, 2.6, 2.65, 2.7]
crberr: [-0.3, -0.25, -0.2, -0.15, -0.1]
m: [0.03, 0.0325, 0.035, 0.0375, 0.04, 0.0425, 0.045, 0.0475, 0.05]

# selected structure
cra_f: 2.50
crb_f: 0.8150
crberr_f: -0.25
m_f: 0.045

# calib pheno
a0: [0.2]
b0: [0.015]
delta: [0.2]

# selected pheno
a0_f: 0.2
b0_f: 0.015
delta_f: 0.2

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 10

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: false
test_years: 0.1
