# data
sites: ["Paracou", "Tapajos"]

# structure
# paste0("[", paste(seq(1.8, 2.2, 0.01), collapse = ", "), "]")
cra: [2.13]
crberr: [-0.4641]
m: [0.025]

# pheno
a0: [0.2]
b0: [0.015]
delta: [0.2]
a0_f: 0.2
b0_f: 0.015
delta_f: 0.2

# sim pars
spinup: 600
verbose: yes
seed: 42
rep: 1

# singularity
troll3: "singularity/troll3/troll3.sif"
troll4: "singularity/troll4/troll4.sif"

# tests
test: true
test_years: 0.1
