---
title: "Fluxes data"
author: Sylvain Schmitt -
date: today
date-format: medium
format: 
  gfm:
    toc: true
    toc-depth: 2
---

This folder contains our point to fluxes data used to evaluate the TROLL model outputs:

-   FLUXNET 2015 fluxes data for Paracou and Tapajos are available with climate data
-   Guyaflux fluxes data for Paracou, namely soil water content (m3/m3), are available with climate data
-   Paracou litterfall were provided by Damien Bonal (D. Bonal pers. com.)
-   Paracou plant area index were provided by Grégoire Vincent (G. Vincent & N. Barbier pers. com.)
-   Tapajos litterfall are available online through the Oak Ridge National Laboratory (ORNL) Distributed Active Archive Center (DAAC): <https://daac.ornl.gov/LBA/guides/CD10_Litter_Tapajos.html>
-   PLUMBER data for leaf area index (LAI) from MODIS were retrieve from Research Data Australia: <https://researchdata.edu.au/plumber2-forcing-evaluation-surface-models/1656048>
-   Tapajos leaf area density (LAD) was retrieved from @smith2019: <https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.15726>
-   Tapajos and Paracou leaf area index (LAI) per age was retrieved from @yang2023: <https://essd.copernicus.org/preprints/essd-2022-436/essd-2022-436.pdf>
-   Tapajos and Paracou Solar Induced Fluorescence (SIF) from TROPOMI satellites retrieved from <https://figshare.com/ndownloader/articles/19336346/versions/2> and processed in the R script get_sif.R resulting in the rtsif.tsv file
-   Tapajos and Paracou leaf area per age from Yang et al. (2023) retrieved from <https://figshare.com/articles/dataset/Leaf_age-dependent_LAI_seasonality_product_Lad-LAI_over_tropical_and_subtropical_evergreen_broadleaved_forests/21700955/4> and processed in the R script get_lai_age.R resulting the lai_age.tsv file.
-   Data_LAI_new.xlsx: LAI seasonality of leaf age cohorts. The first two sheets are observed by Jin Wu. The third one are those predicted by Xiuzhi Chen et al. (pers. com.).
-   Tapajos soil water content from Restrepo-Coupe, Natalia et al. (2023), <https://doi.org/10.2139/ssrn.4442514>

```{r, comment=""}
fs::dir_tree()
```
